name: Docs
version: '${project.version}'
main: me.melarn.docs.Docs
api-version: 1.19
author: Melarn
description: Info about server
commands:
  docs:
    description: Custom help command
    aliases:
      - documentation
      - website
  help:
    description: Help command
  voice:
    aliases:
      - plasmovoice
      - voicechat